import argparse
import os
import time
from valis import registration
import numpy as np
import pyvips

from pathlib import Path
from typing import List

from tqdm import tqdm

from ome_types import OME
from ome_types._autogenerated.ome_2016_06 import (
    Channel,
    TiffData,
    Plane,
    Pixels,
    UnitsLength,
    Image,
)
from ome_types.model.simple_types import ChannelID, PixelsID, ImageID
from valis import slide_tools
from valis import orientation_check
import logging

NUMPY_FORMAT_BF_DTYPE = {
    "uint8": "uint8",
    "int8": "int8",
    "uint16": "uint16",
    "int16": "int16",
    "uint32": "uint32",
    "int32": "int32",
    "float32": "float",
    "float64": "double",
}

logger = logging.getLogger(__name__)


def get_parser():
    parser = argparse.ArgumentParser(description="Align two WSIs.")
    parser.add_argument(
        "--reference",
        type=str,
        help="Path to WSI in .ome.tif format. Will be used as the reference image.",
    )
    parser.add_argument(
        "--image",
        type=str,
        help="Path to WSI in .ome.tif format. Will be used as the warped image.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        help="Output directory.",
    )
    return parser


def setup_valis_logging():
    """Configure detailed stream logging for valis logger"""
    # Get the valis logger
    valis_logger = logging.getLogger("valis")
    valis_logger.setLevel(logging.DEBUG)
    valis_logger.setLevel(logging.DEBUG)

    # Create console handler
    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.DEBUG)

    # Create detailed formatter with line number, function name, etc.
    formatter = logging.Formatter(
        fmt="%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s() - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    console_handler.setFormatter(formatter)

    # Add handler to logger
    valis_logger.addHandler(console_handler)
    valis_logger.addHandler(console_handler)

    return valis_logger


def pyvips_to_thumbnail_array(img: pyvips.Image, size: int) -> "np.ndarray":
    """Render a pyvips image to a small numpy array for orientation scoring.

    Uses pyvips' resize so we never materialize the full slide in memory.
    """
    import numpy as np

    scale = size / max(img.width, img.height)
    small = img.resize(scale)
    if small.bands > 1:
        small = small.colourspace("b-w")
    if small.format == "ushort":
        small = (small >> 8).cast("uchar")
    elif small.format != "uchar":
        small = small.cast("uchar")
    mem = small.write_to_memory()
    return np.frombuffer(mem, dtype=np.uint8).reshape(small.height, small.width)


def check_and_correct_orientation(
    moving_img: pyvips.Image,
    reference_img: pyvips.Image,
    downsample_size: int = 2048,
) -> tuple[pyvips.Image, "orientation_check.OrientationMatch"]:
    """Find the best D4 orientation of ``moving_img`` against ``reference_img``
    and return the corrected pyvips image plus the match info.

    ``downsample_size`` is the requested thumbnail side. If either input is
    smaller than that on its short side, the effective size is clamped down
    so we never upsample.
    """
    max_useful = min(
        reference_img.width,
        reference_img.height,
        moving_img.width,
        moving_img.height,
    )
    effective_size = min(downsample_size, max_useful)
    if effective_size != downsample_size:
        print(
            f"[orientation] requested size {downsample_size} clamped to "
            f"{effective_size} (smaller input side)"
        )

    ref_thumb = pyvips_to_thumbnail_array(reference_img, effective_size)
    mov_thumb = pyvips_to_thumbnail_array(moving_img, effective_size)

    match = orientation_check.find_best_orientation(
        ref_thumb, mov_thumb, downsample_size=effective_size, use_gradient=True
    )

    print("\n=== Orientation check ===")
    print(f"  thumbnail size       : {effective_size}x{effective_size}")
    print(f"  best transform       : {match.name}")
    print(f"  correction needed    : {orientation_check.describe(match)}")
    print(f"  best NCC score       : {match.score:+.4f}")
    identity_score = match.scores["identity"]
    margin = match.score - identity_score
    print(f"  identity NCC score   : {identity_score:+.4f}  (margin: {margin:+.4f})")
    print("  all scores           :")
    for name, score in sorted(match.scores.items(), key=lambda kv: -kv[1]):
        marker = "  <-- chosen" if name == match.name else ""
        print(f"    {name:<14s} {score:+.4f}{marker}")
    if match.k == 0 and not match.mirror:
        print("  >> images already correctly oriented; no pre-rotation applied.")
    else:
        print(
            f"  >> applying {orientation_check.describe(match)} to moving image "
            "before registration."
        )
    print("=========================\n")

    corrected = orientation_check.apply_d4_pyvips(moving_img, match.k, match.mirror)
    return corrected, match


def convert_16to8_bit(image: pyvips.Image, clamp=None):
    if clamp:
        image = (image > clamp).ifthenelse(clamp, image)
    else:
        clamp = 2**16
    tile_processed = ((image / clamp) * 255).cast("uchar")
    return tile_processed.colourspace("b-w")


def warp_new_slide(
    new_img: pyvips.Image,
    registrar: registration.Valis,
    source_img: str,
    dst_img: str,
    bbox_xywh=None,
):
    src_slide_obj = registrar.get_slide(source_img)
    dst_slide_obj = registrar.get_slide(dst_img)

    warped_img = src_slide_obj.warp_img_from_to(new_img, to_slide_obj=dst_slide_obj)

    return warped_img


def create_progress_callback():
    """Create a progress callback for writing the output file."""
    pbar = tqdm(total=100, desc="Writing OME-TIFF", unit="%")
    last_update = time.time()

    def eval_callback(image, progress):
        if (time.time() - last_update) > 0.25:
            # Set the progress bar's current iteration count directly
            pbar.n = progress.percent

            # Refresh the display to show the updated value
            pbar.refresh()

    eval_callback.close = lambda: pbar.close()
    return eval_callback


def vips2bf_dtype(vips_format):
    np_dtype = slide_tools.VIPS_FORMAT_NUMPY_DTYPE[vips_format]
    bf_dtype = NUMPY_FORMAT_BF_DTYPE[str(np_dtype().dtype)]

    return bf_dtype


def create_ome_metadata(
    width: int,
    height: int,
    protein_names: List[str],
    protein_ids: List[str],
    um_per_px: float,
    dtype: str = "uint16",
) -> str:
    """
    Create OME-XML metadata for single or multi-channel protein images.

    Parameters:
    -----------
    width : int
        Image width in pixels
    height : int
        Image height in pixels
    protein_names : list of str
        Human-readable protein name(s), one per channel
    protein_ids : list of str
        Protein identifier(s), one per channel
    um_per_px : float
        Micrometers per pixel
    dtype : str
        Data type (default: 'uint16')

    Returns:
    --------
    str : OME-XML metadata as string
    """

    # Validate inputs
    num_channels = len(protein_names)
    if len(protein_ids) != num_channels:
        raise ValueError(
            f"Length of protein_names ({num_channels}) and protein_ids "
            f"({len(protein_ids)}) must match"
        )

    if num_channels == 0:
        raise ValueError("Must provide at least one protein name and ID")

    # Create the OME structure
    ome = OME()

    # Create Channels
    channels = []
    for c in range(num_channels):
        channel = Channel(
            id=ChannelID(f"Channel:0:{c}"),
            name=protein_names[c],
            samples_per_pixel=1,
        )
        channels.append(channel)

    # Create TiffData blocks
    tiff_data_blocks = []
    for c in range(num_channels):
        tiff_data = TiffData(
            first_z=0,
            first_c=c,
            first_t=0,
            ifd=c,
            plane_count=1,
        )
        tiff_data_blocks.append(tiff_data)

    # Create Planes
    planes = []
    for c in range(num_channels):
        plane = Plane(
            the_z=0,
            the_c=c,
            the_t=0,
        )
        planes.append(plane)

    # Create Pixels
    pixels = Pixels(
        id=PixelsID("Pixels:0"),
        dimension_order="XYZCT",
        size_x=width,
        size_y=height,
        size_z=1,
        size_c=num_channels,
        size_t=1,
        type=dtype,
        big_endian=False,
        physical_size_x=um_per_px,
        physical_size_y=um_per_px,
        physical_size_x_unit=UnitsLength.MICROMETER,
        physical_size_y_unit=UnitsLength.MICROMETER,
        channels=channels,
        tiff_data_blocks=tiff_data_blocks,
        planes=planes,
    )

    # Create Image name from protein info
    if num_channels == 1:
        image_name = f"{protein_names[0]} ({protein_ids[0]})"
    else:
        # For multichannel, create a combined name
        image_name = f"Multichannel ({', '.join(protein_ids)})"

    # Create Image with pixels
    image = Image(
        id=ImageID("Image:0"),
        name=image_name,
        pixels=pixels,
    )

    # Assemble the structure
    ome.images.append(image)

    # Convert to XML string
    return ome.to_xml()


def write_ome_tiff(
    images: list[pyvips.Image],
    names: list[str],
    output_path,
    um_per_px: float,
    scale: float = 1.0,
):
    first_height = images[0].height
    first_width = images[0].width
    first_format = images[0].format
    for img in images:
        if img.width != first_width or img.height != first_height:
            raise ValueError(
                f"mismatched image size:"
                f" {first_width}x{first_height} vs {img.width}x{img.height}"
            )
        if img.format != first_format:
            raise ValueError(f"mismatched format: {first_format} vs {img.format}")
    if scale < 1.0:
        images = [im.resize(scale) for im in images]

    # Only create OME metadata if ome_tiff is True
    ome_xml = create_ome_metadata(
        width=images[0].width,
        height=images[0].height,
        protein_names=names,
        protein_ids=names,
        um_per_px=um_per_px / scale,
        dtype=vips2bf_dtype(images[0].format),
    )

    stacked = pyvips.Image.arrayjoin(images, across=1)
    stacked.set_type(pyvips.GValue.gstr_type, "image-description", ome_xml)
    stacked.set_type(pyvips.GValue.gint_type, "page-height", images[0].height)

    stacked.set_progress(True)
    stacked.signal_connect("eval", create_progress_callback())

    # Append remaining images
    stacked.tiffsave(
        output_path,
        pyramid=True,
        subifd=True,
        tile=True,
        compression="jpeg",
        tile_height=256,
        tile_width=256,
        Q=100,
        bigtiff=True,
    )

    print(f"\nSuccessfully wrote: {output_path}")


def main():
    # Setup logging first
    setup_valis_logging()
    args = get_parser().parse_args()
    Path(args.output_dir).mkdir(parents=True, exist_ok=True)

    img_out_path = os.path.join(args.output_dir, os.path.basename(args.image))
    ref_out_path = os.path.join(args.output_dir, os.path.basename(args.reference))

    # Save 8-bit copy of --reference so valis learns registration from uint8
    if not os.path.exists(ref_out_path):
        ref_img = pyvips.Image.new_from_file(args.reference, page=0)
        if ref_img.format == "ushort":
            ref_img = convert_16to8_bit(ref_img)
        ref_img.set_progress(True)
        cb = create_progress_callback()
        ref_img.signal_connect("eval", cb)
        ref_img.tiffsave(ref_out_path)
        cb.close()

    # Cheap pre-alignment orientation check. If the moving image is rotated or
    # mirrored relative to the reference, bake the correction into the copy
    # that gets handed to Valis so registration only deals with residuals.
    ref_for_check = pyvips.Image.new_from_file(ref_out_path, page=0)
    moving_for_check = pyvips.Image.new_from_file(args.image, page=0)
    _, orient_match = check_and_correct_orientation(
        moving_img=moving_for_check,
        reference_img=ref_for_check,
        downsample_size=2048,
    )

    needs_correction = orient_match.k != 0 or orient_match.mirror
    if not os.path.exists(img_out_path):
        if needs_correction:
            moving_full = pyvips.Image.new_from_file(args.image, page=0)
            corrected = orientation_check.apply_d4_pyvips(
                moving_full, orient_match.k, orient_match.mirror
            )
            corrected.set_progress(True)
            cb = create_progress_callback()
            corrected.signal_connect("eval", cb)
            corrected.tiffsave(img_out_path, bigtiff=True)
            cb.close()
        else:
            os.symlink(os.path.abspath(args.image), img_out_path)

    # Create a Valis object and use it to register the slides in slide_src_dir
    registrar = registration.Valis(
        src_dir=args.output_dir,
        dst_dir=args.output_dir,
        name="registration",
        img_list=[
            os.path.join(args.output_dir, os.path.basename(args.image)),
            os.path.join(args.output_dir, os.path.basename(args.reference)),
        ],
        reference_img_f=os.path.join(args.output_dir, os.path.basename(args.reference)),
        thumbnail_size=4096,
        check_for_reflections=False,
        similarity_metric="euclidean",
        align_to_reference=True,
    )
    registrar.register()

    if not os.path.exists(os.path.join(args.output_dir, "aligned.ome.tif")):
        warped_slides = []
        names = []

        img = pyvips.Image.new_from_file(args.image, page=0)
        if img.format == "ushort":
            img = convert_16to8_bit(img)
        if needs_correction:
            img = orientation_check.apply_d4_pyvips(
                img, orient_match.k, orient_match.mirror
            )
        warped_img = warp_new_slide(
            img,
            registrar,
            source_img=os.path.join(args.output_dir, os.path.basename(args.image)),
            dst_img=os.path.join(args.output_dir, os.path.basename(args.reference)),
        )
        warped_slides.append(warped_img)
        names.append(os.path.basename(args.reference))

        img = pyvips.Image.new_from_file(args.reference, page=0)
        if img.format == "ushort":
            img = convert_16to8_bit(img)
        warped_img = warp_new_slide(
            img,
            registrar,
            source_img=os.path.join(args.output_dir, os.path.basename(args.reference)),
            dst_img=os.path.join(args.output_dir, os.path.basename(args.reference)),
        )
        warped_slides.append(warped_img)
        names.append(os.path.basename(args.reference))

        write_ome_tiff(
            images=warped_slides,
            names=names,
            output_path=os.path.join(args.output_dir, "aligned.ome.tif"),
            um_per_px=0.2,
            scale=1,
        )


if __name__ == "__main__":
    main()
