import argparse
import os
import sys
import time
from valis import registration, feature_matcher, feature_detectors, preprocessing
from valis.serial_rigid import TooFewMatchesError
import numpy as np
import pyvips

from pathlib import Path
from typing import List

from tqdm import tqdm

from ome_types import OME
from ome_types._autogenerated.ome_2016_06 import (
    Channel,
    TiffData,
    Plane,
    Pixels,
    UnitsLength,
    Image,
)
from ome_types.model.simple_types import ChannelID, PixelsID, ImageID
from valis import slide_tools
from valis import orientation_check
import logging

NUMPY_FORMAT_BF_DTYPE = {
    "uint8": "uint8",
    "int8": "int8",
    "uint16": "uint16",
    "int16": "int16",
    "uint32": "uint32",
    "int32": "int32",
    "float32": "float",
    "float64": "double",
}

logger = logging.getLogger(__name__)


def get_parser():
    parser = argparse.ArgumentParser(description="Align two WSIs.")
    parser.add_argument(
        "--reference",
        type=str,
        help="Path to WSI in .ome.tif format. Will be used as the reference image.",
    )
    parser.add_argument(
        "--image",
        type=str,
        help="Path to WSI in .ome.tif format. Will be used as the warped image.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        help="Output directory.",
    )
    parser.add_argument(
        "--max-processed-image-dim-px",
        type=int,
        default=2048,
        help="Max side length used for feature detection / non-rigid registration. "
        "Higher = better matches but more memory; 4096 OOMs on a 32GB laptop.",
    )
    stain_choices = (
        "auto",
        "he-hematoxylin",
        "he-hematoxylin-raw",
        "he-hematoxylin-sparse",
        "inverted-fluorescence",
        "od",
        "colorful-standardizer",
        "luminosity",
    )
    parser.add_argument(
        "--image-stain",
        choices=stain_choices,
        default="auto",
        help="Preprocessor for --image. 'he-hematoxylin' deconvolves H&E and keeps "
        "the hematoxylin (nuclei) channel; 'inverted-fluorescence' un-inverts a "
        "DAPI-style image so nuclei are bright; 'auto' lets valis decide.",
    )
    parser.add_argument(
        "--reference-stain",
        choices=stain_choices,
        default="auto",
        help="Same as --image-stain but for --reference.",
    )
    parser.add_argument(
        "--orientation-margin",
        type=float,
        default=0.0,
        help="Minimum NCC margin (best - identity) required to apply a D4 "
        "pre-rotation. Below this, the script falls back to identity. "
        "Default 0 trusts the winning transform; raise it (e.g. 0.05) only "
        "when the script's heuristic is producing wrong flips.",
    )
    parser.add_argument(
        "--no-script-orientation",
        action="store_true",
        help="Skip the script's own D4 pre-rotation entirely and let valis "
        "handle reflections (via check_for_reflections=True). Useful when the "
        "script's NCC-based orientation check is too noisy on weak/ambiguous "
        "stain pairs.",
    )
    parser.add_argument(
        "--min-rigid-matches",
        type=int,
        default=30,
        help="Minimum number of initial keypoint matches required before "
        "valis's rematch step. Below this, the script aborts with a clear "
        "error instead of letting valis warp the image with a degenerate "
        "transform (which OOMs the rematch's feature detection).",
    )
    return parser


class HematoxylinExtractor(preprocessing.ImageProcesser):
    """Extract the hematoxylin (nuclei) channel from an H&E image.

    Pipeline: Macenko-style normalization against a standard H&E
    reference (so faded slides come back up to consistent intensity),
    then deconvolve using ``skimage.color.rgb2hed`` with the fixed
    Ruifrok-Johnston stain matrix and keep only the H channel.

    Macenko's ``normalize_he`` picks H vs E by an angle heuristic on the
    candidate stain vectors' red component. On eosin-dominant or
    hematoxylin-faded slides that ordering can flip, sending eosin into
    the "hematoxylin" row — yielding an output where stroma lights up
    brighter than nuclei. We detect that here by checking which row
    correlates with bluish pixels in the original RGB (true hematoxylin)
    and swap if needed.

    Pass ``use_macenko=False`` to skip normalization entirely and just
    run ``rgb2hed`` on raw RGB — useful as a fallback when Macenko
    misbehaves on an atypical slide.
    """

    def create_mask(self):
        from valis.preprocessing import create_tissue_mask_from_rgb

        _, tissue_mask = create_tissue_mask_from_rgb(self.image)
        return tissue_mask

    def process_image(
        self,
        *args,
        use_macenko: bool = True,
        sparse: bool = False,
        sparse_pct: float = 90.0,
        sparse_blur_sigma: float = 1.5,
        **kwargs,
    ):
        """Extract hematoxylin channel.

        ``sparse=True`` thresholds the H channel at the ``sparse_pct``
        percentile and zeros everything below — yielding a punctate
        "nuclei dots" image that resembles a fluorescence reference.
        Use this on eosin-dominant / hematoxylin-faded slides where the
        smooth percentile stretch produces stromal texture instead of
        isolated nuclei.
        """
        from skimage.color import rgb2hed

        img = self.image
        if img.ndim != 3 or img.shape[2] < 3:
            raise ValueError("HematoxylinExtractor requires an RGB image")
        rgb = img[..., :3]
        if rgb.dtype != np.uint8:
            rgb = np.clip(rgb, 0, 255).astype(np.uint8)

        rgb_for_unmix = rgb
        if use_macenko:
            # Macenko-style normalization to a standard H&E reference.
            # Brings faded slides up to consistent stain intensity.
            try:
                normalized = preprocessing.normalize_he(
                    rgb, Io=240, alpha=1, beta=0.15
                )
                normalized = _fix_he_swap(normalized, rgb)
                # Reproject normalized concentrations through the
                # canonical Ruifrok-Johnston H/E vectors so rgb2hed below
                # sees a canonical H&E image.
                ref_stain = np.array(
                    [[0.5626, 0.7201, 0.4062], [0.2159, 0.8012, 0.5581]]
                )
                recon_od = ref_stain.T @ normalized
                recon = np.clip(
                    240.0 * np.exp(-recon_od), 0, 255
                ).T.reshape(rgb.shape)
                rgb_for_unmix = recon.astype(np.uint8)
            except Exception:
                # Macenko can fail on degenerate (very faded / very dark)
                # tissue. Fall back to raw RGB rather than aborting.
                rgb_for_unmix = rgb

        hed = rgb2hed(rgb_for_unmix)
        h = hed[..., 0]  # hematoxylin channel (positive where stain is dense)

        if sparse:
            # Restrict the percentile to tissue pixels so a large dark
            # background doesn't pull the threshold down. Then zero
            # everything below the cutoff and stretch the survivors.
            from valis.preprocessing import create_tissue_mask_from_rgb

            try:
                _, tissue_mask = create_tissue_mask_from_rgb(rgb)
                tissue = tissue_mask > 0
            except Exception:
                tissue = np.ones(h.shape, dtype=bool)
            if tissue.sum() < 1000:
                tissue = np.ones(h.shape, dtype=bool)
            cutoff = np.percentile(h[tissue], sparse_pct)
            top = np.percentile(h[tissue], 99.9)
            denom = max(top - cutoff, 1e-6)
            out = np.clip((h - cutoff) / denom, 0.0, 1.0)
            out[~tissue] = 0
            if sparse_blur_sigma > 0:
                # Smooth so each surviving spot becomes a small Gaussian
                # blob with a real local maximum — gives keypoint matchers
                # something with scale to lock onto.
                from scipy.ndimage import gaussian_filter

                out = gaussian_filter(out.astype(np.float32), sparse_blur_sigma)
                m = out.max()
                if m > 0:
                    out = out / m
            return (out * 255).astype(np.uint8)

        lo, hi = np.percentile(h, (1, 99))
        if hi <= lo:
            hi = lo + 1e-6
        h = np.clip((h - lo) / (hi - lo), 0.0, 1.0)
        return (h * 255).astype(np.uint8)


def _fix_he_swap(normalized: np.ndarray, rgb: np.ndarray) -> np.ndarray:
    """Detect and correct H/E row swaps from Macenko's angle heuristic.

    Hematoxylin stains pixels blue-purple, eosin pink-red. So the true
    hematoxylin concentration row should correlate positively with
    (B - R) across the image, while eosin should anti-correlate. If the
    rows are swapped, swap them back.
    """
    flat = rgb.reshape(-1, 3).astype(np.float32)
    blueness = flat[:, 2] - flat[:, 0]  # B - R
    # Mask to tissue pixels (anything sufficiently darker than 240 bg)
    od_proxy = 255.0 - flat.mean(axis=1)
    tissue = od_proxy > 15.0
    if tissue.sum() < 1000:
        return normalized
    b = blueness[tissue]
    if b.std() < 1e-3:
        return normalized
    c0 = np.corrcoef(normalized[0, tissue], b)[0, 1]
    c1 = np.corrcoef(normalized[1, tissue], b)[0, 1]
    if np.isnan(c0) or np.isnan(c1):
        return normalized
    if c1 > c0:
        return normalized[::-1].copy()
    return normalized


class InvertedFluorescence(preprocessing.ImageProcesser):
    """Reverse the inversion on an 'inverted DAPI' (or similar) greyscale image
    so that nuclei come out bright — matching the convention of hematoxylin
    deconvolution output.
    """

    def create_mask(self):
        img = self.image
        if img.ndim == 3:
            img = img.mean(axis=-1)
        img = img.astype(np.float32)
        # In an inverted-fluorescence image, tissue is dark on a bright bg.
        thresh = np.percentile(img, 90)
        mask = (img < thresh).astype(np.uint8) * 255
        return mask

    def process_image(self, *args, **kwargs):
        img = self.image
        if img.ndim == 3:
            img = img.mean(axis=-1)
        img = img.astype(np.float32)
        lo, hi = np.percentile(img, (1, 99))
        if hi <= lo:
            hi = lo + 1.0
        img = np.clip((img - lo) / (hi - lo), 0.0, 1.0)
        inverted = 1.0 - img
        return (inverted * 255).astype(np.uint8)


def setup_valis_logging():
    """Configure detailed stream logging for valis logger"""
    # Get the valis logger
    valis_logger = logging.getLogger("valis")
    valis_logger.setLevel(logging.DEBUG)
    valis_logger.setLevel(logging.DEBUG)

    # Create console handler
    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.DEBUG)

    # Create detailed formatter with line number, function name, etc.
    formatter = logging.Formatter(
        fmt="%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s() - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    console_handler.setFormatter(formatter)

    # Add handler to logger
    valis_logger.addHandler(console_handler)
    valis_logger.addHandler(console_handler)

    return valis_logger


def pyvips_to_thumbnail_array(img: pyvips.Image, size: int) -> "np.ndarray":
    """Render a pyvips image to a small numpy array for orientation scoring.

    Uses pyvips' resize so we never materialize the full slide in memory.
    """
    import numpy as np

    scale = size / max(img.width, img.height)
    small = img.resize(scale)
    if small.bands > 1:
        small = small.colourspace("b-w")
    if small.format == "ushort":
        small = (small >> 8).cast("uchar")
    elif small.format != "uchar":
        small = small.cast("uchar")
    mem = small.write_to_memory()
    return np.frombuffer(mem, dtype=np.uint8).reshape(small.height, small.width)


def pyvips_to_thumbnail_rgb_array(img: pyvips.Image, size: int) -> "np.ndarray":
    """Render a pyvips image to a small RGB numpy array. Used to feed
    color-aware preprocessors (HEDeconvolution, HematoxylinFixed, OD, ...)
    on a thumbnail prior to the orientation check.
    """
    scale = size / max(img.width, img.height)
    small = img.resize(scale)
    if small.format == "ushort":
        small = (small >> 8).cast("uchar")
    elif small.format != "uchar":
        small = small.cast("uchar")
    if small.bands == 1:
        small = small.bandjoin([small, small])
    elif small.bands > 3:
        small = small[0].bandjoin([small[1], small[2]])
    mem = small.write_to_memory()
    return np.frombuffer(mem, dtype=np.uint8).reshape(
        small.height, small.width, 3
    )


def run_processor_on_thumbnail(
    processor_spec, thumb_array: "np.ndarray", src_f: str
) -> "np.ndarray":
    """Instantiate a valis ``ImageProcesser`` subclass on a thumbnail and
    return its ``process_image`` output. Used so the orientation check
    sees the same nuclei-bright signal that valis will register on,
    rather than raw luminance of two visually dissimilar stains.
    """
    cls, kwargs = processor_spec
    proc = cls(image=thumb_array, src_f=src_f, level=0, series=0)
    return proc.process_image(**(kwargs or {}))


def check_and_correct_orientation(
    moving_img: pyvips.Image,
    reference_img: pyvips.Image,
    downsample_size: int = 2048,
    margin_threshold: float = 0.05,
    moving_processor=None,
    reference_processor=None,
    moving_src_f: str = "",
    reference_src_f: str = "",
) -> tuple[pyvips.Image, "orientation_check.OrientationMatch"]:
    """Find the best D4 orientation of ``moving_img`` against ``reference_img``
    and return the corrected pyvips image plus the match info.

    ``downsample_size`` is the requested thumbnail side. If either input is
    smaller than that on its short side, the effective size is clamped down
    so we never upsample.

    If ``moving_processor`` / ``reference_processor`` are provided, the
    corresponding side is preprocessed with that valis ``ImageProcesser``
    before the NCC scoring. This is what makes the check usable across
    stains: comparing raw luminance of (e.g.) H&E vs. inverted DAPI is
    essentially noise, but comparing extracted hematoxylin vs. un-inverted
    DAPI gives a strong, anatomically-aligned signal.
    """
    max_useful = min(
        reference_img.width,
        reference_img.height,
        moving_img.width,
        moving_img.height,
    )
    effective_size = min(downsample_size, max_useful)
    if effective_size != downsample_size:
        print(
            f"[orientation] requested size {downsample_size} clamped to "
            f"{effective_size} (smaller input side)"
        )

    if reference_processor is not None:
        rgb = pyvips_to_thumbnail_rgb_array(reference_img, effective_size)
        ref_thumb = run_processor_on_thumbnail(
            reference_processor, rgb, reference_src_f
        )
    else:
        ref_thumb = pyvips_to_thumbnail_array(reference_img, effective_size)
    if moving_processor is not None:
        rgb = pyvips_to_thumbnail_rgb_array(moving_img, effective_size)
        mov_thumb = run_processor_on_thumbnail(
            moving_processor, rgb, moving_src_f
        )
    else:
        mov_thumb = pyvips_to_thumbnail_array(moving_img, effective_size)

    match = orientation_check.find_best_orientation(
        ref_thumb, mov_thumb, downsample_size=effective_size, use_gradient=True
    )

    print("\n=== Orientation check ===")
    print(f"  thumbnail size       : {effective_size}x{effective_size}")
    print(f"  best transform       : {match.name}")
    print(f"  correction needed    : {orientation_check.describe(match)}")
    print(f"  best NCC score       : {match.score:+.4f}")
    identity_score = match.scores["identity"]
    margin = match.score - identity_score
    print(f"  identity NCC score   : {identity_score:+.4f}  (margin: {margin:+.4f})")
    print("  all scores           :")
    for name, score in sorted(match.scores.items(), key=lambda kv: -kv[1]):
        marker = "  <-- chosen" if name == match.name else ""
        print(f"    {name:<14s} {score:+.4f}{marker}")
    inconclusive = (
        margin_threshold > 0
        and (match.k != 0 or match.mirror)
        and margin < margin_threshold
    )
    if inconclusive:
        print(
            f"  >> margin {margin:+.4f} below threshold {margin_threshold}; "
            "treating orientation check as inconclusive and using identity."
        )
        match = orientation_check.OrientationMatch(
            name="identity",
            k=0,
            mirror=False,
            score=identity_score,
            scores=match.scores,
        )
    elif match.k == 0 and not match.mirror:
        print("  >> images already correctly oriented; no pre-rotation applied.")
    else:
        print(
            f"  >> applying {orientation_check.describe(match)} to moving image "
            "before registration."
        )
    print("=========================\n")

    corrected = orientation_check.apply_d4_pyvips(moving_img, match.k, match.mirror)
    return corrected, match


def convert_16to8_bit(image: pyvips.Image, clamp=None):
    if clamp:
        image = (image > clamp).ifthenelse(clamp, image)
    else:
        clamp = 2**16
    tile_processed = ((image / clamp) * 255).cast("uchar")
    return tile_processed.colourspace("b-w")


def warp_new_slide(
    new_img: pyvips.Image,
    registrar: registration.Valis,
    source_img: str,
    dst_img: str,
    bbox_xywh=None,
):
    src_slide_obj = registrar.get_slide(source_img)
    dst_slide_obj = registrar.get_slide(dst_img)

    warped_img = src_slide_obj.warp_img_from_to(new_img, to_slide_obj=dst_slide_obj)

    return warped_img


def create_progress_callback():
    """Create a progress callback for writing the output file."""
    pbar = tqdm(total=100, desc="Writing OME-TIFF", unit="%")
    last_update = time.time()

    def eval_callback(image, progress):
        if (time.time() - last_update) > 0.25:
            # Set the progress bar's current iteration count directly
            pbar.n = progress.percent

            # Refresh the display to show the updated value
            pbar.refresh()

    eval_callback.close = lambda: pbar.close()
    return eval_callback


def vips2bf_dtype(vips_format):
    np_dtype = slide_tools.VIPS_FORMAT_NUMPY_DTYPE[vips_format]
    bf_dtype = NUMPY_FORMAT_BF_DTYPE[str(np_dtype().dtype)]

    return bf_dtype


def create_ome_metadata(
    width: int,
    height: int,
    protein_names: List[str],
    protein_ids: List[str],
    um_per_px: float,
    dtype: str = "uint16",
) -> str:
    """
    Create OME-XML metadata for single or multi-channel protein images.

    Parameters:
    -----------
    width : int
        Image width in pixels
    height : int
        Image height in pixels
    protein_names : list of str
        Human-readable protein name(s), one per channel
    protein_ids : list of str
        Protein identifier(s), one per channel
    um_per_px : float
        Micrometers per pixel
    dtype : str
        Data type (default: 'uint16')

    Returns:
    --------
    str : OME-XML metadata as string
    """

    # Validate inputs
    num_channels = len(protein_names)
    if len(protein_ids) != num_channels:
        raise ValueError(
            f"Length of protein_names ({num_channels}) and protein_ids "
            f"({len(protein_ids)}) must match"
        )

    if num_channels == 0:
        raise ValueError("Must provide at least one protein name and ID")

    # Create the OME structure
    ome = OME()

    # Create Channels
    channels = []
    for c in range(num_channels):
        channel = Channel(
            id=ChannelID(f"Channel:0:{c}"),
            name=protein_names[c],
            samples_per_pixel=1,
        )
        channels.append(channel)

    # Create TiffData blocks
    tiff_data_blocks = []
    for c in range(num_channels):
        tiff_data = TiffData(
            first_z=0,
            first_c=c,
            first_t=0,
            ifd=c,
            plane_count=1,
        )
        tiff_data_blocks.append(tiff_data)

    # Create Planes
    planes = []
    for c in range(num_channels):
        plane = Plane(
            the_z=0,
            the_c=c,
            the_t=0,
        )
        planes.append(plane)

    # Create Pixels
    pixels = Pixels(
        id=PixelsID("Pixels:0"),
        dimension_order="XYZCT",
        size_x=width,
        size_y=height,
        size_z=1,
        size_c=num_channels,
        size_t=1,
        type=dtype,
        big_endian=False,
        physical_size_x=um_per_px,
        physical_size_y=um_per_px,
        physical_size_x_unit=UnitsLength.MICROMETER,
        physical_size_y_unit=UnitsLength.MICROMETER,
        channels=channels,
        tiff_data_blocks=tiff_data_blocks,
        planes=planes,
    )

    # Create Image name from protein info
    if num_channels == 1:
        image_name = f"{protein_names[0]} ({protein_ids[0]})"
    else:
        # For multichannel, create a combined name
        image_name = f"Multichannel ({', '.join(protein_ids)})"

    # Create Image with pixels
    image = Image(
        id=ImageID("Image:0"),
        name=image_name,
        pixels=pixels,
    )

    # Assemble the structure
    ome.images.append(image)

    # Convert to XML string
    return ome.to_xml()


def write_ome_tiff(
    images: list[pyvips.Image],
    names: list[str],
    output_path,
    um_per_px: float,
    scale: float = 1.0,
):
    first_height = images[0].height
    first_width = images[0].width
    first_format = images[0].format
    for img in images:
        if img.width != first_width or img.height != first_height:
            raise ValueError(
                f"mismatched image size:"
                f" {first_width}x{first_height} vs {img.width}x{img.height}"
            )
        if img.format != first_format:
            raise ValueError(f"mismatched format: {first_format} vs {img.format}")
    if scale < 1.0:
        images = [im.resize(scale) for im in images]

    # Only create OME metadata if ome_tiff is True
    ome_xml = create_ome_metadata(
        width=images[0].width,
        height=images[0].height,
        protein_names=names,
        protein_ids=names,
        um_per_px=um_per_px / scale,
        dtype=vips2bf_dtype(images[0].format),
    )

    stacked = pyvips.Image.arrayjoin(images, across=1)
    stacked.set_type(pyvips.GValue.gstr_type, "image-description", ome_xml)
    stacked.set_type(pyvips.GValue.gint_type, "page-height", images[0].height)

    stacked.set_progress(True)
    stacked.signal_connect("eval", create_progress_callback())

    # Append remaining images
    stacked.tiffsave(
        output_path,
        pyramid=True,
        subifd=True,
        tile=True,
        compression="jpeg",
        tile_height=256,
        tile_width=256,
        Q=100,
        bigtiff=True,
    )

    print(f"\nSuccessfully wrote: {output_path}")


def main():
    # Setup logging first
    setup_valis_logging()
    args = get_parser().parse_args()
    Path(args.output_dir).mkdir(parents=True, exist_ok=True)

    print("=== align_two_images invocation ===", flush=True)
    print(f"  argv         : {' '.join(sys.argv)}", flush=True)
    print(f"  cwd          : {os.getcwd()}", flush=True)
    for k, v in sorted(vars(args).items()):
        print(f"  {k:<24}: {v}", flush=True)
    print("===================================", flush=True)


    img_out_path = os.path.join(args.output_dir, os.path.basename(args.image))
    ref_out_path = os.path.join(args.output_dir, os.path.basename(args.reference))

    # Save 8-bit copy of --reference so valis learns registration from uint8
    if not os.path.exists(ref_out_path):
        ref_img = pyvips.Image.new_from_file(args.reference, page=0)
        if ref_img.format == "ushort":
            ref_img = convert_16to8_bit(ref_img)
        ref_img.set_progress(True)
        cb = create_progress_callback()
        ref_img.signal_connect("eval", cb)
        ref_img.tiffsave(ref_out_path)
        cb.close()

    # Build a per-image processor dict so we can force nuclei-extraction on
    # both sides — H&E -> hematoxylin channel, inverted DAPI -> un-inverted
    # greyscale. Both end up "nuclei = bright", which gives the matcher
    # something common to lock onto across modalities. We also feed these
    # processors into the orientation check below so it scores nuclei-vs-
    # nuclei rather than raw luminance of two visually different stains.
    stain_to_processor = {
        "he-hematoxylin": [HematoxylinExtractor, {}],
        "he-hematoxylin-raw": [HematoxylinExtractor, {"use_macenko": False}],
        "he-hematoxylin-sparse": [HematoxylinExtractor, {"sparse": True}],
        "inverted-fluorescence": [InvertedFluorescence, {}],
        "od": [preprocessing.OD, {}],
        "colorful-standardizer": [preprocessing.ColorfulStandardizer, {}],
        "luminosity": [preprocessing.Luminosity, {}],
    }

    # `auto` resolves *here*, not inside valis. Valis's default for a 1-band
    # uchar (assumed-fluorescence) input is to leave polarity untouched —
    # which silently breaks cross-modal matching when the input is *inverted*
    # DAPI (dark nuclei on bright bg). We pick a real processor based on
    # bands + mean intensity so 'nuclei = bright' on both sides, which is
    # what the matcher actually needs.
    def _resolve_auto_stain(path: str) -> str:
        peek = pyvips.Image.new_from_file(path, page=0)
        thumb = pyvips_to_thumbnail_array(peek, 256)
        mean = float(thumb.mean())
        if peek.bands >= 3:
            return "he-hematoxylin"
        # single-band: high mean => bright bg (inverted DAPI), un-invert
        return "inverted-fluorescence" if mean > 127 else "luminosity"

    if args.image_stain == "auto":
        args.image_stain = _resolve_auto_stain(args.image)
        print(f"[auto-stain] --image -> {args.image_stain}")
    if args.reference_stain == "auto":
        args.reference_stain = _resolve_auto_stain(args.reference)
        print(f"[auto-stain] --reference -> {args.reference_stain}")

    reference_path = os.path.join(
        args.output_dir, os.path.basename(args.reference)
    )

    # Cheap pre-alignment orientation check. If the moving image is rotated or
    # mirrored relative to the reference, bake the correction into the copy
    # that gets handed to Valis so registration only deals with residuals.
    if args.no_script_orientation:
        print("[orientation] script orientation check disabled (--no-script-orientation)")
        orient_match = orientation_check.OrientationMatch(
            name="identity", k=0, mirror=False, score=0.0, scores={}
        )
    else:
        ref_for_check = pyvips.Image.new_from_file(ref_out_path, page=0)
        moving_for_check = pyvips.Image.new_from_file(args.image, page=0)
        _, orient_match = check_and_correct_orientation(
            moving_img=moving_for_check,
            reference_img=ref_for_check,
            downsample_size=2048,
            margin_threshold=args.orientation_margin,
            moving_processor=stain_to_processor.get(args.image_stain),
            reference_processor=stain_to_processor.get(args.reference_stain),
            moving_src_f=args.image,
            reference_src_f=args.reference,
        )

    needs_correction = orient_match.k != 0 or orient_match.mirror
    if needs_correction:
        # Write the D4-corrected moving image to a distinct filename so we
        # don't collide with — and silently skip — an already-existing copy
        # at ``img_out_path`` (which happens whenever ``args.output_dir``
        # is the same directory as the input).
        stem, ext = os.path.splitext(os.path.basename(args.image))
        suffix = f"_k{orient_match.k}_m{int(orient_match.mirror)}"
        img_out_path = os.path.join(args.output_dir, f"{stem}{suffix}{ext}")
    if not os.path.exists(img_out_path):
        if needs_correction:
            print(
                f"[orientation] writing D4-corrected copy to {img_out_path}",
                flush=True,
            )
            moving_full = pyvips.Image.new_from_file(args.image, page=0)
            corrected = orientation_check.apply_d4_pyvips(
                moving_full, orient_match.k, orient_match.mirror
            )
            corrected.set_progress(True)
            cb = create_progress_callback()
            corrected.signal_connect("eval", cb)
            corrected.tiffsave(img_out_path, bigtiff=True)
            cb.close()
        else:
            os.symlink(os.path.abspath(args.image), img_out_path)

    # Build the processor_dict against the *final* registered file paths,
    # which differ from the raw inputs when we wrote a D4-corrected copy.
    image_path = img_out_path
    processor_dict = {}
    if args.image_stain != "auto":
        processor_dict[image_path] = stain_to_processor[args.image_stain]
    if args.reference_stain != "auto":
        processor_dict[reference_path] = stain_to_processor[args.reference_stain]

    # Create a Valis object and use it to register the slides in slide_src_dir
    registrar = registration.Valis(
        src_dir=args.output_dir,
        dst_dir=args.output_dir,
        name="registration",
        img_list=[image_path, reference_path],
        reference_img_f=reference_path,
        thumbnail_size=4096,
        max_processed_image_dim_px=args.max_processed_image_dim_px,
        max_image_dim_px=args.max_processed_image_dim_px,
        min_rigid_matches=args.min_rigid_matches,
        check_for_reflections=False,
        similarity_metric="euclidean",
        align_to_reference=True,
    )
    matches_dir = os.path.join(args.output_dir, "registration", "matches")
    try:
        registrar.register(
            processor_dict=processor_dict if processor_dict else None,
        )
    except TooFewMatchesError as e:
        # Try to dump whatever matches valis did find before bailing — the
        # serial-rigid registrar holds the initial-pass match_dict at this
        # point, which is exactly what the user needs to diagnose the
        # failure. Pipeline.draw_matches isn't usable yet (relies on
        # post-rigid attributes), so build the viz from match_dict directly.
        try:
            from valis import viz as _viz, warp_tools as _wt
            os.makedirs(matches_dir, exist_ok=True)
            srr = registrar.rigid_registrar
            for moving_idx, fixed_idx in srr.iter_order:
                moving = srr.img_obj_list[moving_idx]
                fixed = srr.img_obj_list[fixed_idx]
                m = fixed.match_dict.get(moving)
                if m is None:
                    continue
                img1 = _wt.resize_img(moving.image, moving.image.shape[:2])
                img2 = _wt.resize_img(fixed.image, fixed.image.shape[:2])
                viz_img = _viz.draw_matches(
                    src_img=img1,
                    kp1_xy=m.matched_kp2_xy,
                    dst_img=img2,
                    kp2_xy=m.matched_kp1_xy,
                    rad=3,
                    alignment="horizontal",
                )
                out_f = os.path.join(
                    matches_dir,
                    f"failed_{moving.name}_to_{fixed.name}_matches.png",
                )
                _wt.save_img(out_f, viz_img)
                print(f"Saved pre-failure match viz: {out_f}")
        except Exception as draw_err:
            print(f"(could not draw matches: {draw_err})")
        print(f"\nALIGNMENT ABORTED: {e}", flush=True)
        raise SystemExit(2)

    registrar.draw_matches(matches_dir)
    print(f"Saved feature-match visualization to {matches_dir}")

    if not os.path.exists(os.path.join(args.output_dir, "aligned.ome.tif")):
        warped_slides = []
        names = []

        img = pyvips.Image.new_from_file(args.image, page=0)
        if img.format == "ushort":
            img = convert_16to8_bit(img)
        if needs_correction:
            img = orientation_check.apply_d4_pyvips(
                img, orient_match.k, orient_match.mirror
            )
        warped_img = warp_new_slide(
            img,
            registrar,
            source_img=image_path,
            dst_img=reference_path,
        )
        warped_slides.append(warped_img)
        names.append(os.path.basename(args.reference))

        img = pyvips.Image.new_from_file(args.reference, page=0)
        if img.format == "ushort":
            img = convert_16to8_bit(img)
        warped_img = warp_new_slide(
            img,
            registrar,
            source_img=reference_path,
            dst_img=reference_path,
        )
        warped_slides.append(warped_img)
        names.append(os.path.basename(args.reference))

        write_ome_tiff(
            images=warped_slides,
            names=names,
            output_path=os.path.join(args.output_dir, "aligned.ome.tif"),
            um_per_px=0.2,
            scale=1,
        )


if __name__ == "__main__":
    main()
