"""The slow, full-registration alignment flow, extracted from
``scripts/align_two_images.py`` so both the CLI and the web app can call it.

The public entry point is :func:`run_alignment`. Lower-level helpers
(``convert_16to8_bit``, ``write_ome_tiff``, ``check_and_correct_orientation``,
...) are exposed for reuse and testing.
"""

import os
import pickle
import shutil
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, List, Optional

import numpy as np
import pyvips
from skimage import transform
from tqdm import tqdm

from ome_types import OME
from ome_types._autogenerated.ome_2016_06 import (
    Channel,
    TiffData,
    Plane,
    Pixels,
    UnitsLength,
    Image,
)
from ome_types.model.simple_types import ChannelID, PixelsID, ImageID

from valis import (
    feature_detectors,
    feature_matcher,
    registration,
    orientation_check,
    slide_tools,
)
from valis.serial_rigid import TooFewMatchesError
from valis.interactive import processors

NUMPY_FORMAT_BF_DTYPE = {
    "uint8": "uint8",
    "int8": "int8",
    "uint16": "uint16",
    "int16": "int16",
    "uint32": "uint32",
    "int32": "int32",
    "float32": "float",
    "float64": "double",
}

# The sparse-hematoxylin fallback sweep. Each (pct, sigma) gives a different
# density / blob-size tradeoff; we try several before giving up.
SPARSE_SWEEP = [
    {"sparse_pct": 90.0, "sparse_blur_sigma": 1.5},
    {"sparse_pct": 85.0, "sparse_blur_sigma": 2.0},
    {"sparse_pct": 95.0, "sparse_blur_sigma": 1.0},
    {"sparse_pct": 80.0, "sparse_blur_sigma": 2.5},
    {"sparse_pct": 97.0, "sparse_blur_sigma": 1.5},
]

# User-facing filter names (see ``processors.MATCHER_SCHEMA``) -> valis names.
# "none" only affects which matches the web preview displays; the matcher
# itself always filters (rigid registration needs inliers), so it falls back
# to MAGSAC.
MATCH_FILTER_NAMES = {
    "magsac": feature_matcher.USAC_MAGSAC_NAME,
    "ransac": feature_matcher.RANSAC_NAME,
    # No GMS: LightGlueMatcher filters via filter_matches_ransac, which only
    # knows the RANSAC family.
}


# ---------------------------------------------------------------------------
# Feature detector / matcher construction
# ---------------------------------------------------------------------------


def build_detector(
    detector: str = "disk", max_keypoints: int = 7500, matcher: str = "lightglue"
):
    """Build the feature detector named in ``processors.MATCHER_SCHEMA``.

    LoMa only works with its own DaD + DeDoDe-G features, so
    ``matcher="loma-b"`` ignores ``detector``.
    """
    if matcher == "loma-b":
        return feature_detectors.LoMaFD(num_features=int(max_keypoints))
    if matcher != "lightglue":
        raise ValueError(f"unknown matcher: {matcher!r}")
    if detector == "disk":
        return feature_detectors.DiskFD(num_features=int(max_keypoints))
    if detector == "dedode":
        return feature_detectors.DeDoDeFD(num_features=int(max_keypoints))
    raise ValueError(f"unknown detector: {detector!r}")


def build_matcher(
    detector: str = "disk",
    max_keypoints: int = 7500,
    ransac_thresh: float = 7,
    filter_method: str = "magsac",
    matcher: str = "lightglue",
    feature_detector=None,
):
    """Build a LightGlue or LoMa matcher from the ``processors.MATCHER_SCHEMA``
    knobs.

    Shared by the web app's live preview and :func:`run_alignment`, so the
    full registration matches with the same settings the user tuned.
    ``feature_detector`` reuses an existing detector instead of building one.
    """
    if feature_detector is None:
        feature_detector = build_detector(detector, max_keypoints, matcher)
    matcher_cls = (
        feature_matcher.LoMaMatcher
        if matcher == "loma-b"
        else feature_matcher.LightGlueMatcher
    )
    return matcher_cls(
        feature_detector=feature_detector,
        match_filter_method=MATCH_FILTER_NAMES.get(
            filter_method, feature_matcher.USAC_MAGSAC_NAME
        ),
        ransac_thresh=int(ransac_thresh),
    )


@dataclass
class PreviewMatch:
    """Matches the web app displayed, used verbatim for rigid registration.

    ``kp_moving`` / ``kp_reference`` are paired (N, 2) xy arrays in the pixel
    space of ``moving_img`` / ``reference_img``: the preprocessed working
    images the user saw (moving image already flipped/shifted).
    """

    kp_moving: np.ndarray
    kp_reference: np.ndarray
    moving_img: np.ndarray
    reference_img: np.ndarray


def _thumb_to_full_M(thumb_shape_rc, full_wh):
    """3x3 mapping thumbnail xy -> full-resolution xy (pixel-centre aligned)."""
    sx = full_wh[0] / thumb_shape_rc[1]
    sy = full_wh[1] / thumb_shape_rc[0]
    return np.array(
        [[sx, 0, 0.5 * sx - 0.5], [0, sy, 0.5 * sy - 0.5], [0, 0, 1]], dtype=float
    )


def preview_affine_full_res(preview: PreviewMatch, moving_full_wh, reference_full_wh):
    """Similarity fit to the preview's matches, lifted to full resolution.

    Returns ``(A, T)``: ``T`` maps moving-thumbnail xy -> reference-thumbnail
    xy; ``A`` maps full-resolution moving xy (after flip/shift) ->
    full-resolution reference xy.
    """
    T = transform.SimilarityTransform.from_estimate(
        np.asarray(preview.kp_moving, dtype=float),
        np.asarray(preview.kp_reference, dtype=float),
    )
    if not T:
        raise AlignmentError("could not fit a transform to the preview matches")
    mov_M = _thumb_to_full_M(preview.moving_img.shape[:2], moving_full_wh)
    ref_M = _thumb_to_full_M(preview.reference_img.shape[:2], reference_full_wh)
    A = ref_M @ T.params @ np.linalg.inv(mov_M)
    return A, T.params


def apply_affine_pyvips(img: pyvips.Image, A, out_wh) -> pyvips.Image:
    """Warp ``img`` by the forward 3x3 ``A`` onto an ``out_wh`` canvas."""
    return img.affine(
        [A[0, 0], A[0, 1], A[1, 0], A[1, 1]],
        odx=A[0, 2],
        ody=A[1, 2],
        oarea=[0, 0, int(out_wh[0]), int(out_wh[1])],
        interpolate=pyvips.Interpolate.new("bilinear"),
        extend="black",
    )


def _save_preview_matches(preview: PreviewMatch, matches_dir):
    """Save the matches that drove rigid registration (the preview's)."""
    from valis import viz, warp_tools

    os.makedirs(matches_dir, exist_ok=True)
    viz_img = viz.draw_matches(
        src_img=preview.moving_img,
        kp1_xy=preview.kp_moving,
        dst_img=preview.reference_img,
        kp2_xy=preview.kp_reference,
        rad=3,
        alignment="horizontal",
    )
    warp_tools.save_img(os.path.join(matches_dir, "preview_matches.png"), viz_img)


# ---------------------------------------------------------------------------
# Thumbnail-based orientation check
# ---------------------------------------------------------------------------


def run_processor_on_thumbnail(processor_spec, thumb_array, src_f):
    """Backwards-compatible re-export (see ``processors``)."""
    return processors.run_processor_on_thumbnail(processor_spec, thumb_array, src_f)


def check_and_correct_orientation(
    moving_img: pyvips.Image,
    reference_img: pyvips.Image,
    downsample_size: int = 2048,
    margin_threshold: float = 0.05,
    moving_processor=None,
    reference_processor=None,
    moving_src_f: str = "",
    reference_src_f: str = "",
):
    """Find the best D4 orientation of ``moving_img`` against ``reference_img``
    and return ``(corrected_pyvips_image, OrientationMatch)``.

    If ``moving_processor`` / ``reference_processor`` are provided, the
    corresponding side is preprocessed with that valis ``ImageProcesser``
    before NCC scoring — this is what makes the check usable across stains.
    """
    max_useful = min(
        reference_img.width,
        reference_img.height,
        moving_img.width,
        moving_img.height,
    )
    effective_size = min(downsample_size, max_useful)
    if effective_size != downsample_size:
        print(
            f"[orientation] requested size {downsample_size} clamped to "
            f"{effective_size} (smaller input side)"
        )

    if reference_processor is not None:
        rgb = processors.pyvips_to_thumbnail_rgb_array(reference_img, effective_size)
        ref_thumb = processors.run_processor_on_thumbnail(
            reference_processor, rgb, reference_src_f
        )
    else:
        ref_thumb = processors.pyvips_to_thumbnail_array(reference_img, effective_size)
    if moving_processor is not None:
        rgb = processors.pyvips_to_thumbnail_rgb_array(moving_img, effective_size)
        mov_thumb = processors.run_processor_on_thumbnail(
            moving_processor, rgb, moving_src_f
        )
    else:
        mov_thumb = processors.pyvips_to_thumbnail_array(moving_img, effective_size)

    match = orientation_check.find_best_orientation(
        ref_thumb, mov_thumb, downsample_size=effective_size, use_gradient=True
    )

    print("\n=== Orientation check ===")
    print(f"  thumbnail size       : {effective_size}x{effective_size}")
    print(f"  best transform       : {match.name}")
    print(f"  correction needed    : {orientation_check.describe(match)}")
    print(f"  best NCC score       : {match.score:+.4f}")
    identity_score = match.scores["identity"]
    margin = match.score - identity_score
    print(f"  identity NCC score   : {identity_score:+.4f}  (margin: {margin:+.4f})")
    print("  all scores           :")
    for name, score in sorted(match.scores.items(), key=lambda kv: -kv[1]):
        marker = "  <-- chosen" if name == match.name else ""
        print(f"    {name:<14s} {score:+.4f}{marker}")
    inconclusive = (
        margin_threshold > 0
        and (match.k != 0 or match.mirror)
        and margin < margin_threshold
    )
    if inconclusive:
        print(
            f"  >> margin {margin:+.4f} below threshold {margin_threshold}; "
            "treating orientation check as inconclusive and using identity."
        )
        match = orientation_check.OrientationMatch(
            name="identity",
            k=0,
            mirror=False,
            score=identity_score,
            scores=match.scores,
        )
    elif match.k == 0 and not match.mirror:
        print("  >> images already correctly oriented; no pre-rotation applied.")
    else:
        print(
            f"  >> applying {orientation_check.describe(match)} to moving image "
            "before registration."
        )
    print("=========================\n")

    corrected = orientation_check.apply_d4_pyvips(moving_img, match.k, match.mirror)
    return corrected, match


# ---------------------------------------------------------------------------
# Image conversion / warping / writing
# ---------------------------------------------------------------------------


def convert_16to8_bit(image: pyvips.Image, clamp=None):
    if clamp:
        image = (image > clamp).ifthenelse(clamp, image)
    else:
        clamp = 2**16
    tile_processed = ((image / clamp) * 255).cast("uchar")
    return tile_processed.colourspace("b-w")


def warp_new_slide(new_img, registrar, source_img, dst_img, bbox_xywh=None):
    src_slide_obj = registrar.get_slide(source_img)
    dst_slide_obj = registrar.get_slide(dst_img)
    return src_slide_obj.warp_img_from_to(new_img, to_slide_obj=dst_slide_obj)


def create_progress_callback():
    """Create a pyvips ``eval`` progress callback for writing the output file."""
    pbar = tqdm(total=100, desc="Writing OME-TIFF", unit="%")
    last_update = time.time()

    def eval_callback(image, progress):
        if (time.time() - last_update) > 0.25:
            pbar.n = progress.percent
            pbar.refresh()

    eval_callback.close = lambda: pbar.close()
    return eval_callback


def vips2bf_dtype(vips_format):
    np_dtype = slide_tools.VIPS_FORMAT_NUMPY_DTYPE[vips_format]
    return NUMPY_FORMAT_BF_DTYPE[str(np_dtype().dtype)]


def create_ome_metadata(
    width: int,
    height: int,
    protein_names: List[str],
    protein_ids: List[str],
    um_per_px: float,
    dtype: str = "uint16",
) -> str:
    """Create OME-XML metadata for single or multi-channel images."""
    num_channels = len(protein_names)
    if len(protein_ids) != num_channels:
        raise ValueError(
            f"Length of protein_names ({num_channels}) and protein_ids "
            f"({len(protein_ids)}) must match"
        )
    if num_channels == 0:
        raise ValueError("Must provide at least one protein name and ID")

    ome = OME()
    channels = [
        Channel(
            id=ChannelID(f"Channel:0:{c}"), name=protein_names[c], samples_per_pixel=1
        )
        for c in range(num_channels)
    ]
    tiff_data_blocks = [
        TiffData(first_z=0, first_c=c, first_t=0, ifd=c, plane_count=1)
        for c in range(num_channels)
    ]
    planes = [Plane(the_z=0, the_c=c, the_t=0) for c in range(num_channels)]

    pixels = Pixels(
        id=PixelsID("Pixels:0"),
        dimension_order="XYZCT",
        size_x=width,
        size_y=height,
        size_z=1,
        size_c=num_channels,
        size_t=1,
        type=dtype,
        big_endian=False,
        physical_size_x=um_per_px,
        physical_size_y=um_per_px,
        physical_size_x_unit=UnitsLength.MICROMETER,
        physical_size_y_unit=UnitsLength.MICROMETER,
        channels=channels,
        tiff_data_blocks=tiff_data_blocks,
        planes=planes,
    )

    if num_channels == 1:
        image_name = f"{protein_names[0]} ({protein_ids[0]})"
    else:
        image_name = f"Multichannel ({', '.join(protein_ids)})"

    image = Image(id=ImageID("Image:0"), name=image_name, pixels=pixels)
    ome.images.append(image)
    return ome.to_xml()


def write_ome_tiff(
    images: List[pyvips.Image],
    names: List[str],
    output_path,
    um_per_px: float,
    scale: float = 1.0,
):
    first_height = images[0].height
    first_width = images[0].width
    first_format = images[0].format
    for img in images:
        if img.width != first_width or img.height != first_height:
            raise ValueError(
                f"mismatched image size:"
                f" {first_width}x{first_height} vs {img.width}x{img.height}"
            )
        if img.format != first_format:
            raise ValueError(f"mismatched format: {first_format} vs {img.format}")
    if scale < 1.0:
        images = [im.resize(scale) for im in images]

    ome_xml = create_ome_metadata(
        width=images[0].width,
        height=images[0].height,
        protein_names=names,
        protein_ids=names,
        um_per_px=um_per_px / scale,
        dtype=vips2bf_dtype(images[0].format),
    )

    stacked = pyvips.Image.arrayjoin(images, across=1)
    stacked.set_type(pyvips.GValue.gstr_type, "image-description", ome_xml)
    stacked.set_type(pyvips.GValue.gint_type, "page-height", images[0].height)

    stacked.set_progress(True)
    stacked.signal_connect("eval", create_progress_callback())

    stacked.tiffsave(
        output_path,
        pyramid=True,
        subifd=True,
        tile=True,
        compression="jpeg",
        tile_height=256,
        tile_width=256,
        Q=100,
        bigtiff=True,
    )

    print(f"\nSuccessfully wrote: {output_path}")


# ---------------------------------------------------------------------------
# Full alignment orchestration
# ---------------------------------------------------------------------------


def _build_processor_dict(
    image_path,
    image_stain,
    image_params,
    reference_path,
    reference_stain,
    reference_params,
):
    """Build ``{path: [Cls, kwargs]}`` from stain names + explicit param
    overrides. ``*_params`` are merged on top of the registry defaults.
    """
    pd = {}
    if image_stain and image_stain != "auto":
        cls, kw = processors.PROCESSOR_REGISTRY[image_stain]
        pd[image_path] = [cls, {**kw, **(image_params or {})}]
    if reference_stain and reference_stain != "auto":
        cls, kw = processors.PROCESSOR_REGISTRY[reference_stain]
        pd[reference_path] = [cls, {**kw, **(reference_params or {})}]
    return pd


def _dump_failed_matches(registrar, matches_dir):
    """Dump whatever matches valis found before bailing, for diagnosis."""
    try:
        from valis import viz as _viz, warp_tools as _wt

        os.makedirs(matches_dir, exist_ok=True)
        srr = registrar.rigid_registrar
        for moving_idx, fixed_idx in srr.iter_order:
            moving = srr.img_obj_list[moving_idx]
            fixed = srr.img_obj_list[fixed_idx]
            m = fixed.match_dict.get(moving)
            if m is None:
                continue
            img1 = _wt.resize_img(moving.image, moving.image.shape[:2])
            img2 = _wt.resize_img(fixed.image, fixed.image.shape[:2])
            viz_img = _viz.draw_matches(
                src_img=img1,
                kp1_xy=m.matched_kp2_xy,
                dst_img=img2,
                kp2_xy=m.matched_kp1_xy,
                rad=3,
                alignment="horizontal",
            )
            out_f = os.path.join(
                matches_dir, f"failed_{moving.name}_to_{fixed.name}_matches.png"
            )
            _wt.save_img(out_f, viz_img)
            print(f"Saved pre-failure match viz: {out_f}")
    except Exception as draw_err:
        print(f"(could not draw matches: {draw_err})")


class AlignmentError(RuntimeError):
    """Raised when registration cannot produce enough matches to align."""


def run_alignment(
    image_path: str,
    reference_path: str,
    output_dir: str,
    image_stain: str = "auto",
    reference_stain: str = "auto",
    image_params: Optional[dict] = None,
    reference_params: Optional[dict] = None,
    image_geometry: Optional[dict] = None,
    max_processed_image_dim_px: int = 2048,
    min_rigid_matches: int = 30,
    orientation_margin: float = 0.0,
    no_script_orientation: bool = False,
    matcher_cfg: Optional[dict] = None,
    preview_match: Optional[PreviewMatch] = None,
    progress_cb: Optional[Callable[[str, float, str], None]] = None,
) -> str:
    """Run the full two-image alignment and write ``aligned.ome.tif``.

    Parameters mirror the CLI flags. ``image_params`` / ``reference_params``
    override the per-processor kwargs (used by the web app's sliders).
    ``image_geometry`` is a flip/translate pre-transform for the moving image
    (see ``processors.GEOMETRY_DEFAULTS``), applied at full resolution before
    the orientation check, registration and the final warp. A manual flip
    disables the automatic D4 orientation check so it can't undo the flip.
    ``matcher_cfg`` holds :func:`build_matcher` kwargs (the web app's
    detector/matcher controls); ``None`` keeps valis's default matcher.
    ``preview_match`` (web app): a coarse pre-alignment. The similarity
    transform fit to the matches the user saw is applied to the moving image
    with pyvips, so valis starts from an image that is roughly in the
    reference's frame (flips, large rotations/offsets resolved) and then runs
    its normal rigid + non-rigid registration. The automatic orientation check
    and the sparse-hematoxylin fallback are skipped (the user chose the
    orientation and processor settings), and valis's tissue crop and intensity
    normalization are off so its rigid matching sees what the web app's
    pre-aligned check showed. Every pre-transform applied to the
    moving image is recorded in ``<output_dir>/preproc_transforms.pickle``.
    ``progress_cb(stage, fraction, message)`` is called at coarse milestones.

    Returns the path to the written ``aligned.ome.tif``.
    """

    def _progress(stage, frac, msg=""):
        if progress_cb is not None:
            progress_cb(stage, frac, msg)

    Path(output_dir).mkdir(parents=True, exist_ok=True)

    # valis resizes to exactly this dim, upsampling small images. DISK's memory
    # grows steeply with image size, so never process above native resolution.
    native_dim = max(
        max(im.width, im.height)
        for im in (
            pyvips.Image.new_from_file(image_path, page=0),
            pyvips.Image.new_from_file(reference_path, page=0),
        )
    )
    max_processed_image_dim_px = min(max_processed_image_dim_px, native_dim)

    img_out_path = os.path.join(output_dir, os.path.basename(image_path))
    ref_out_path = os.path.join(output_dir, os.path.basename(reference_path))

    _progress("prepare", 0.02, "writing 8-bit reference copy")
    if not os.path.exists(ref_out_path):
        ref_img = pyvips.Image.new_from_file(reference_path, page=0)
        if ref_img.format == "ushort":
            ref_img = convert_16to8_bit(ref_img)
        ref_img.set_progress(True)
        cb = create_progress_callback()
        ref_img.signal_connect("eval", cb)
        ref_img.tiffsave(ref_out_path)
        cb.close()

    # Resolve auto stains.
    if image_stain == "auto":
        image_stain = processors.resolve_auto_stain(image_path)
        print(f"[auto-stain] --image -> {image_stain}")
    if reference_stain == "auto":
        reference_stain = processors.resolve_auto_stain(reference_path)
        print(f"[auto-stain] --reference -> {reference_stain}")

    reference_path_final = ref_out_path

    image_geometry = processors.normalize_geometry(image_geometry)
    needs_geometry = not processors.geometry_is_identity(image_geometry)
    if needs_geometry:
        print(f"[geometry] moving-image pre-transform: {image_geometry}")
    user_flipped = image_geometry["flip_h"] or image_geometry["flip_v"]

    # Orientation pre-check.
    _progress("orientation", 0.08, "checking orientation")
    if no_script_orientation or user_flipped or preview_match is not None:
        if preview_match is not None:
            reason = "using preview matches"
        else:
            reason = "manual flip set" if user_flipped else "disabled"
        print(f"[orientation] script orientation check skipped ({reason})")
        orient_match = orientation_check.OrientationMatch(
            name="identity", k=0, mirror=False, score=0.0, scores={}
        )
    else:
        ref_for_check = pyvips.Image.new_from_file(ref_out_path, page=0)
        moving_for_check = processors.apply_geometry_pyvips(
            pyvips.Image.new_from_file(image_path, page=0), image_geometry
        )

        def _orientation_processor(stain):
            # Gray-input processors (fluorescence, channel-getter) operate on a
            # single band and crash on the RGB thumbnail the check feeds them;
            # score those on raw greyscale NCC instead.
            if processors.PROCESSOR_INPUT.get(stain) == "gray":
                return None
            return processors.PROCESSOR_REGISTRY.get(stain)

        _, orient_match = check_and_correct_orientation(
            moving_img=moving_for_check,
            reference_img=ref_for_check,
            downsample_size=2048,
            margin_threshold=orientation_margin,
            moving_processor=_orientation_processor(image_stain),
            reference_processor=_orientation_processor(reference_stain),
            moving_src_f=image_path,
            reference_src_f=reference_path,
        )

    needs_correction = orient_match.k != 0 or orient_match.mirror
    moving_src = pyvips.Image.new_from_file(image_path, page=0)
    reference_src = pyvips.Image.new_from_file(reference_path, page=0)
    ref_wh = (reference_src.width, reference_src.height)

    preview_A = preview_T = None
    if preview_match is not None:
        preview_A, preview_T = preview_affine_full_res(
            preview_match, (moving_src.width, moving_src.height), ref_wh
        )
        print(f"[preview] full-resolution affine to reference frame:\n{preview_A}")

    def _pretransform(img):
        """Flip/shift, D4 orientation, then the preview affine, in that order."""
        if needs_geometry:
            img = processors.apply_geometry_pyvips(img, image_geometry)
        if needs_correction:
            img = orientation_check.apply_d4_pyvips(
                img, orient_match.k, orient_match.mirror
            )
        if preview_A is not None:
            img = apply_affine_pyvips(img, preview_A, ref_wh)
        return img

    needs_pretransform = needs_correction or needs_geometry or preview_A is not None
    if needs_pretransform:
        stem, ext = os.path.splitext(os.path.basename(image_path))
        suffix = ""
        if needs_geometry:
            suffix += processors.geometry_tag(image_geometry)
        if needs_correction:
            suffix += f"_k{orient_match.k}_m{int(orient_match.mirror)}"
        if preview_A is not None:
            suffix += "_prealigned"
        img_out_path = os.path.join(output_dir, f"{stem}{suffix}{ext}")

    with open(os.path.join(output_dir, "preproc_transforms.pickle"), "wb") as f:
        pickle.dump(
            {
                "image_path": image_path,
                "reference_path": reference_path,
                "prealigned_image_path": img_out_path,
                # Applied to the moving image in this order:
                "order": ["geometry", "orientation", "preview_affine"],
                "geometry": image_geometry,
                "orientation": {
                    "name": orient_match.name,
                    "k": orient_match.k,
                    "mirror": orient_match.mirror,
                },
                # Forward 3x3, full-res moving xy (after geometry and
                # orientation) -> full-res reference xy; None if not used.
                "preview_affine": preview_A,
                "preview_affine_out_wh": ref_wh if preview_A is not None else None,
                # Forward 3x3 fit on the preview thumbnails, and its inputs.
                "preview_similarity_thumb": preview_T,
                "preview_kp_moving": (
                    None if preview_match is None else preview_match.kp_moving
                ),
                "preview_kp_reference": (
                    None if preview_match is None else preview_match.kp_reference
                ),
                "preview_moving_shape_rc": (
                    None
                    if preview_match is None
                    else preview_match.moving_img.shape[:2]
                ),
                "preview_reference_shape_rc": (
                    None
                    if preview_match is None
                    else preview_match.reference_img.shape[:2]
                ),
            },
            f,
        )

    if not os.path.exists(img_out_path):
        if needs_pretransform:
            print(f"[pretransform] writing pre-transformed copy to {img_out_path}")
            corrected = _pretransform(moving_src)
            corrected.set_progress(True)
            cb = create_progress_callback()
            corrected.signal_connect("eval", cb)
            corrected.tiffsave(img_out_path, bigtiff=True)
            cb.close()
        else:
            os.symlink(os.path.abspath(image_path), img_out_path)

    image_path_final = img_out_path
    matches_dir = os.path.join(output_dir, "registration", "matches")
    last_registrar = {"obj": None}

    valis_kwargs = {}
    if preview_match is not None:
        # Prepare images the way the web app's pre-aligned check does, so its
        # match count describes what valis's rigid step actually sees.
        valis_kwargs.update(crop_for_rigid_reg=False, norm_method=None)
    if matcher_cfg is not None:
        # Use the tuned matcher for valis's initial "sorting" match too.
        # Otherwise valis first matches with its default VGG + RANSAC sorting
        # matcher and enforces ``min_rigid_matches`` on *that* count, before
        # the tuned matcher ever runs -- so the live preview could show 60
        # matches while registration aborts on 6. Same matcher class + detector
        # also means valis skips its rematch pass.
        tuned = build_matcher(**matcher_cfg)
        valis_kwargs["matcher"] = tuned
        valis_kwargs["matcher_for_sorting"] = tuned

    def _attempt_register(processor_dict):
        reg_dir = os.path.join(output_dir, "registration")
        if os.path.isdir(reg_dir):
            shutil.rmtree(reg_dir)
        registrar = registration.Valis(
            **valis_kwargs,
            src_dir=output_dir,
            dst_dir=output_dir,
            name="registration",
            img_list=[image_path_final, reference_path_final],
            reference_img_f=reference_path_final,
            # Always exactly two images: nothing to order.
            imgs_ordered=True,
            thumbnail_size=max_processed_image_dim_px,
            max_processed_image_dim_px=max_processed_image_dim_px,
            max_image_dim_px=max_processed_image_dim_px,
            min_rigid_matches=min_rigid_matches,
            check_for_reflections=False,
            similarity_metric="euclidean",
            align_to_reference=True,
        )
        last_registrar["obj"] = registrar
        registrar.register(processor_dict=processor_dict if processor_dict else None)
        return registrar

    _progress("register", 0.15, "running rigid + non-rigid registration")
    primary_pd = _build_processor_dict(
        image_path_final,
        image_stain,
        image_params,
        reference_path_final,
        reference_stain,
        reference_params,
    )
    try:
        registrar = _attempt_register(primary_pd)
    except TooFewMatchesError as e:
        if preview_match is not None:
            # Don't silently swap in different processor settings.
            if last_registrar["obj"] is not None:
                _dump_failed_matches(last_registrar["obj"], matches_dir)
            raise AlignmentError(
                f"valis rigid registration (after preview pre-alignment): {e}"
            ) from e
        registrar = _run_sparse_fallback(
            e,
            image_stain,
            reference_stain,
            image_path_final,
            reference_path_final,
            _attempt_register,
            last_registrar,
            matches_dir,
        )

    _progress("matches", 0.80, "drawing match visualization")
    registrar.draw_matches(matches_dir)
    if preview_match is not None:
        _save_preview_matches(preview_match, matches_dir)
    print(f"Saved feature-match visualization to {matches_dir}")

    aligned_path = os.path.join(output_dir, "aligned.ome.tif")
    if not os.path.exists(aligned_path):
        _progress("warp", 0.85, "warping slides")
        warped_slides = []
        names = []

        img = pyvips.Image.new_from_file(image_path, page=0)
        if img.format == "ushort":
            img = convert_16to8_bit(img)
        img = _pretransform(img)
        warped_img = warp_new_slide(
            img, registrar, source_img=image_path_final, dst_img=reference_path_final
        )
        warped_slides.append(warped_img)
        names.append(os.path.basename(image_path))

        img = pyvips.Image.new_from_file(reference_path, page=0)
        if img.format == "ushort":
            img = convert_16to8_bit(img)
        warped_img = warp_new_slide(
            img,
            registrar,
            source_img=reference_path_final,
            dst_img=reference_path_final,
        )
        warped_slides.append(warped_img)
        names.append(os.path.basename(reference_path))

        _progress("write", 0.92, "writing aligned OME-TIFF")
        write_ome_tiff(
            images=warped_slides,
            names=names,
            output_path=aligned_path,
            um_per_px=0.2,
            scale=1,
        )

    _progress("done", 1.0, "alignment complete")
    return aligned_path


def _run_sparse_fallback(
    err,
    image_stain,
    reference_stain,
    image_path_final,
    reference_path_final,
    attempt_register,
    last_registrar,
    matches_dir,
):
    """On too-few-matches with hematoxylin, sweep the sparse extractor."""
    fb_image_stain = (
        "he-hematoxylin-sparse" if image_stain == "he-hematoxylin" else image_stain
    )
    fb_reference_stain = (
        "he-hematoxylin-sparse"
        if reference_stain == "he-hematoxylin"
        else reference_stain
    )
    has_fallback = (
        fb_image_stain != image_stain or fb_reference_stain != reference_stain
    )
    if not has_fallback:
        if last_registrar["obj"] is not None:
            _dump_failed_matches(last_registrar["obj"], matches_dir)
        raise AlignmentError(str(err))

    registrar = None
    last_err = None
    for i, sparse_kwargs in enumerate(SPARSE_SWEEP, start=1):
        label = (
            f"pct={sparse_kwargs['sparse_pct']}, "
            f"sigma={sparse_kwargs['sparse_blur_sigma']}"
        )
        print(
            f"[fallback {i}/{len(SPARSE_SWEEP)}] retrying with sparse hematoxylin "
            f"extractor (image={fb_image_stain}, reference={fb_reference_stain}, "
            f"{label})"
        )
        fb_pd = _build_processor_dict(
            image_path_final,
            fb_image_stain,
            sparse_kwargs,
            reference_path_final,
            fb_reference_stain,
            sparse_kwargs,
        )
        try:
            registrar = attempt_register(fb_pd)
            break
        except TooFewMatchesError as e2:
            last_err = e2
            continue
    if registrar is None:
        if last_registrar["obj"] is not None:
            _dump_failed_matches(last_registrar["obj"], matches_dir)
        raise AlignmentError(
            f"exhausted sparse sweep ({len(SPARSE_SWEEP)} attempts). "
            f"Last error: {last_err}"
        )
    return registrar
